// DreamCatcher Service Worker
// Handles push notifications and caching

import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notifications ────────────────────────────────────────────────────────
self.addEventListener('push', function(event) {
  if (!event.data) return

  let data = {}
  try {
    data = event.data.json()
  } catch(e) {
    data = { notification: { title: 'DreamCatcher', body: event.data.text() } }
  }

  const notification = data.notification || data
  const title   = notification.title || 'DreamCatcher'
  const options = {
    body:  notification.body  || '',
    icon:  '/app/icon-192.png',
    badge: '/app/icon-192.png',
    data:  notification.data  || {},
    requireInteraction: false,
    silent: false
  }

  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

self.addEventListener('notificationclick', function(event) {
  event.notification.close()
  const url = event.notification.data?.url || '/app/'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(windowClients => {
      for (const client of windowClients) {
        if (client.url.includes('/app') && 'focus' in client) {
          return client.focus()
        }
      }
      return clients.openWindow(url)
    })
  )
})
